"use client";
import React, { useMemo } from "react";
import { useLoadScript } from "@react-google-maps/api";
import Map from "./components/Map";
import SearchBar from "./components/SearchBar";
import LocationButton from "./components/LocationButton";
// import ResultMarkers from "./components/ResultMarkers";
import Providers from "./components/Providers";
import { GlobalContextComponent } from "./contexts/globalContext";
import { MarkerContextProvider } from "./contexts/hoverMarkerContext";
import "./globals.css";
import { Raleway } from "next/font/google";

const raleway = Raleway({ weight: "400", subsets: ["latin"] });
// matadata不可在client component export
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const libraries = ["places", "routes"];

export default function RootLayout({ children }) {
  const { isLoaded } = useLoadScript({
    googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
    libraries: useMemo(() => libraries, []),
    region: "TW",
    language: "zh-TW",
  });
  return (
    <html lang="en">
      <body className={`${raleway.className}`}>
        {isLoaded && (
          <Providers>
            <GlobalContextComponent>
              <div className="relative h-screen w-full">
                <MarkerContextProvider>
                  <Map />
                  {children}
                </MarkerContextProvider>
              </div>
              <SearchBar />
              <LocationButton />
            </GlobalContextComponent>
          </Providers>
        )}
      </body>
    </html>
  );
}
